"""Add illustration fields to TranslationJob

Revision ID: a8315bd200a6
Revises: 391a749ff797
Create Date: 2025-08-30 11:54:30.146763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8315bd200a6'
down_revision: Union[str, Sequence[str], None] = '391a749ff797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translation_jobs', sa.Column('illustrations_enabled', sa.Boolean(), nullable=True))
    op.add_column('translation_jobs', sa.Column('illustrations_config', sa.JSON(), nullable=True))
    op.add_column('translation_jobs', sa.Column('illustrations_data', sa.JSON(), nullable=True))
    op.add_column('translation_jobs', sa.Column('illustrations_status', sa.String(), nullable=True))
    op.add_column('translation_jobs', sa.Column('illustrations_count', sa.Integer(), nullable=True))
    op.add_column('translation_jobs', sa.Column('illustrations_directory', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translation_jobs', 'illustrations_directory')
    op.drop_column('translation_jobs', 'illustrations_count')
    op.drop_column('translation_jobs', 'illustrations_status')
    op.drop_column('translation_jobs', 'illustrations_data')
    op.drop_column('translation_jobs', 'illustrations_config')
    op.drop_column('translation_jobs', 'illustrations_enabled')
    # ### end Alembic commands ###
