"""Add illustrations_progress field

Revision ID: b2e468b624fb
Revises: a8315bd200a6
Create Date: 2025-08-30 19:26:41.590287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2e468b624fb'
down_revision: Union[str, Sequence[str], None] = 'a8315bd200a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translation_jobs', sa.Column('illustrations_progress', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translation_jobs', 'illustrations_progress')
    # ### end Alembic commands ###
